name: price-update
run-name: ${{ github.actor }} is starting out GitHub Actions 🚀
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ls
      run: ls
    - name: Init
      run: bash ./priceUpdate/init.sh
    - name: file find chack
      run: ls
    - name: package.json chack
      run: more ./package.json
